@startditaa
                   +---+                         legend          
                   |CLI|                           +-------+     
                   ++--+                           |lab CLI|     
    change request  | ^ revise examples based on   +-------+     
    and review      v | reviewers' feedback        /--------\    
    discussion /------+----\                       |human in|    
    +--------->|contributor|                       |the loop|    
    |          \-----+-----/                       \--------/    
    |                | create/update PR            +------------+
    |                |                             |backend cGRE|
    v 1. initial PR  |                             +------------+
/--------\ review    v                                           
|reviewer|<---->pull request                                     
\--+-+---/           |                                           
   |^| initial       v                                           
   ||| checks   +---------+                                      
   ||| pass     |Synthetic|                                      
   ||+--------->|Data cGRE|<---simple recipe           
   ||           |Generator|      e.g. 50 samples per PR.
   || 2. review +----+----+      this could be merged with  
   || generated      |           full SDG if we decide to
   || samples        v           generate all samples upfront
   |+-----------data samples                                     
   |                 |                                           
   | samples         v                                           
   | approved  +-----------+                                     
   |           |full SDG   |                                     
   +---------->|and trainer|                                     
               |       cGRE|
               +-----------+                                     
@endditaa