# SPDX-License-Identifier: Apache-2.0

name: Lint Markdown documents

on:
  push:
    branches:
      - "main"
    paths:
      - '**/*.md'
      - '.markdownlint-cli2.yaml'
      - '.github/workflows/docs.yml' # This workflow
  pull_request:
    branches:
      - "main"
    paths:
      - '**/*.md'
      - '.markdownlint-cli2.yaml'
      - '.github/workflows/docs.yml' # This workflow

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Harden Runner"
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - name: "Checkout"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: "Check Markdown documents"
        uses: DavidAnson/markdownlint-cli2-action@05f32210e84442804257b2a6f20b273450ec8265 # v19.1.0
        with:
          globs: '**/*.md'
